## Jekyll site settings
title: ZacBook.net
url: http://zacbook.net # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
author: Zachary T. Harmany, PhD
email: your-email@domain.com
description: > # this means to ignore newlines until "permalink:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: /:year-:month-:day/:title
simple_search: http://google.com/search

# Comments
# Globally enables comments, if disqus is configured below. Individual posts
# can override 'comments' to disable on a post-by-post basis.
comments: true

# Social links and integration
social:
  disqus: "zacbook" # For Disqus comments
  email: zac@zacbook.net
  twitter: zacbook
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  tumblr: #username
  github: zacbook
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  lastfm: #username
  dribbble: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  disqus-shortname: #don't see this in social-links
  bing-verify: #don't see this in social-links

# Build settings
markdown: kramdown
highlighter: rouge
gems: ['jekyll-paginate']
paginate: 3

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock


## Octopress configuration settings
# Default extension for new posts and pages
post_ext: md
page_ext: md

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

## Dev notes
# - Update extra components such as font-awesome, bootstrap, and jquery
# - Revisit mathjax config and pandoc processing
# - Compress About and Colophon into a single about page for simplicity?
# - Work on archive display, steal from leonids
# - Decide if the /pages/ directory is a good idea versus manual placement?
# - 404 page
# - Search box
# - cute social button links from leonids
#   Can generalize to allow page / post authors with
#   {% if page.author %} {% assign author = site.data.authors[page.author] %}{% else %}{% assign author = site.owner %} {% endif %}

# CSS Issues
# - CSS on archive page (from leonids) or use template from jekyll-clean
# - CSS on share boxes at the end of posts (from leonids)
# - CSS style on feature images (from leonids)
# - CSS on the contact page (link shown in small view when social icons not shown in nav bar)

